### ISSUE TITLE
Задачи

### ISSUE THREAD

**Issue by Astrarog** [hse-malloc/malloc#1]
### Минимальные требования
- [x] Рандомизация адресов 
- [ ] ~~Замена sbrk на brk~~
- [x] Очистка кода от Си

### Стабильный релиз
- [x] Использование mmap при аллокации большого объема данных
- [ ] [realloc(3)](https://man7.org/linux/man-pages/man3/realloc.3.html) с использованием [mremap(2)](https://man7.org/linux/man-pages/man2/mremap.2.html)
- [x] RAII
- [x] Написание тестов
- [x] Кодирование is_available и size в одно поле (т.к. для is_available нужен лишь 1 бит информации)
- [ ] (optional) Размер выделенного блога больше, чем size_t (использование Bignum)
- [ ] Учесть случай, когда размер страницы меньше, чем `sizeof(MemoryControlBlock) + 1 + sizeof(MemoryControlBlock)`

### Максимальный результат
- [x] Склеивание смежных пустых блоков
- [ ] thread-safe
- [ ] Индексация занятого/свободного места (хеш-таблица)
- [ ] Подсчёт количества ссылок на блок

## Сборка проекта
- [ ] Разрешение конфликта имён со стандартной библиотекой Си
- [ ] Возможность выбора статической/динамической библиотеки
- [ ] Бандлинг (возможность таскать библиотеку с собой в подкаталоге)
- [x] Написание FindMalloc.cmake
- [x] Автоматическая установка библиотеки в стандартные пути
- [x] Автоматизация сборки тестов совместно со сборкой библиотеки
- [ ] Создание версии сборки как модуля ядра Linux
- [ ] (optional) Использование NTC-Cmake для упрощения жизни

**Comment by mitinarseny** [comment]
> * Написание FindMalloc.cmake

[`find_package()`](https://cmake.org/cmake/help/latest/command/find_package.html) умеет работать в двух режимах: `Config` и `Module`. Первый предпочтительнее, т.к. второй нужен для проектов, которые не используют (либо криво используют) CMake. Поэтому предлагаю использовать `malloc-config.cmake`. В текущей версии, он [создается](https://github.com/hse-malloc/malloc/blob/56571a0016259788039a16994c62bf7dce55cfb9/CMakeLists.txt#L42) автоматически при `cmake --install <build_dir>` с помощью [`install(EXPORT)`](https://cmake.org/cmake/help/latest/command/install.html#export)

**Comment by Astrarog** [comment]
> с помощью [`install(EXPORT)`](https://cmake.org/cmake/help/latest/command/install.html#export)

В документации CMake настоятельно [рекомендуют не использовать](https://cmake.org/cmake/help/latest/command/install.html#installing-exports) `install(EXPORT)`.
Исходя из этого эта функциональность была переложена на [`CMakePackageConfigHelpers`](https://github.com/hse-malloc/malloc/blob/aae49b29e25f971d34ea751e16bfa887d31b5e3d/CMakeLists.txt#L49)
