### ISSUE TITLE
Use getrandom(2) or /dev/urandom device for rand seed

### ISSUE THREAD

**Issue by mitinarseny** [hse-malloc/malloc#11]
`timeToInt()` is not secure enough to use. We should seed PRNG with `getrandom(2)` or `/dev/urandom` device.
Here is analogy in Go: https://golang.org/pkg/crypto/rand/#pkg-variables

**Comment by Astrarog** [comment]
Done in [this](https://github.com/hse-malloc/malloc/commit/bace52d73ba11568ff9dae16b73ed09a519981f1) version
