### ISSUE TITLE
C++ new and delete operators

### ISSUE THREAD

**Issue by mitinarseny** [hse-malloc/malloc#4]
Check if we should replace default [`new`](https://en.cppreference.com/w/cpp/memory/new/operator_new) and [`delete`](https://en.cppreference.com/w/cpp/memory/new/operator_delete) operators implementations with our custom ones.

Maybe there is no need for it if their default implementations internally call [`std::malloc`](https://en.cppreference.com/w/cpp/memory/c/malloc) which we link to our implementation?

**Comment by Astrarog** [comment]
Нужно решить, как будем отличать владеюще указатели от каких-то случайных.
Лебедев ПА предлагает следующее соглашение: чистые указатели (void *) никогда не являются владеющими, а владеющие находятся в обетке (по типу shared_ptr и unique_ptr)
С другой стороны в C++ Core Guidelines, [https://github.com/isocpp/CppCoreGuidelines] (GSL), считают, что любые сырыет указатели - это артефакт Си их для синтаксического разграничения лучше обернуть как владеющие, так и не владеющие указатели
Чего придерживаться - вопрос открытый

**Comment by kovdan01** [comment]
> Нужно решить, как будем отличать владеюще указатели от каких-то случайных.
> Лебедев ПА предлагает следующее соглашение: чистые указатели (void *) никогда не являются владеющими, а владеющие находятся в обетке (по типу shared_ptr и unique_ptr)
> С другой стороны в C++ Core Guidelines, [https://github.com/isocpp/CppCoreGuidelines] (GSL), считают, что любые сырыет указатели - это артефакт Си их для синтаксического разграничения лучше обернуть как владеющие, так и не владеющие указатели
> Чего придерживаться - вопрос открытый

В комьюнити широко используется вариант Лебедева П.А., внутри своего кода можно самому с собой договориться использовать сырые указатели исключительно в смысле невладеющих. Если какой-то внешний код использует сырые указатели как владеющие - нужно писать RAII-обертки
