### ISSUE TITLE
Ensure process-safety

### ISSUE THREAD

**Issue by mitinarseny** [hse-malloc/malloc#8]
As shared libraries code [is mapped](https://akkadia.org/drepper/dsohowto.pdf) into virtual address space of process which is dynamically linked to these libraries. So we should check if static objects can be common for multiple processes using the library.

**Comment by Astrarog** [comment]
Only the code is mapped. So when `malloc` from `libmalloc.so` is called the process only reads the instructions and execute them in its own address space.
