### ISSUE TITLE
std::malloc should be noexcept

### ISSUE THREAD

**Issue by mitinarseny** [hse-malloc/malloc#9]
According to documentation of [`std::malloc`](https://en.cppreference.com/w/cpp/memory/c/malloc):
> On success, returns the pointer to the beginning of newly allocated memory. To avoid a memory leak, the returned pointer must be deallocated with std::free() or std::realloc().
> On failure, returns a null pointer.

So, `std::malloc` should be [`noexcept`](https://en.cppreference.com/w/cpp/language/noexcept_spec)?

However, operators  [`new`](https://en.cppreference.com/w/cpp/memory/new/operator_new) and [`delete`](https://en.cppreference.com/w/cpp/memory/new/operator_delete) can throw and, moreover, should have both throwing and non-throwing versions.

**Comment by Astrarog** [comment]
Yes it should.
Several standart library components rely on the fact that errors passes in C style with `errno`. So if `std::malloc` is replaced with custom throwing version then it will be a lot of troubles...
